### ISSUE TITLE
datasheet and layout links do not work

### ISSUE THREAD

**Issue by pdp7** [NextThingCo/nextthingco.github.io#1]
I went to http://nextthingco.github.io which redirected to http://docs.nextthing.co/

These links do not seem to work:

C.H.I.P alpha v0.2 layout
http://docs.nextthing.co/#chip-layout

Allwinner R8 Datasheet
http://docs.nextthing.co/#r8-datasheet

**Comment by elevenarms** [comment]
@pdp7 Check here -> https://github.com/NextThingCo/CHIP-Hardware/tree/master

**Comment by elevenarms** [comment]
Updated the index to include links to the new repo
